// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ServiceClientGenerator.Generators.SourceFiles
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\repos\aws-sdk-net-staging\generator\ServiceClientGeneratorLib\Generators\SourceFiles\BasePaginator.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class BasePaginator : BaseGenerator
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 6 "C:\repos\aws-sdk-net-staging\generator\ServiceClientGeneratorLib\Generators\SourceFiles\BasePaginator.tt"

	AddLicenseHeader();

            
            #line default
            #line hidden
            this.Write(@"
using System;
using System.Collections.Generic;
using System.Text;
using System.Collections;
using System.Threading;
using System.Threading.Tasks;
using Amazon.Runtime;
using Amazon.Util.Internal;

#pragma warning disable CS0612,CS0618
namespace ");
            
            #line 20 "C:\repos\aws-sdk-net-staging\generator\ServiceClientGeneratorLib\Generators\SourceFiles\BasePaginator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Config.Namespace));
            
            #line default
            #line hidden
            this.Write(".Model\r\n{\r\n    /// <summary>\r\n    /// Base class for ");
            
            #line 23 "C:\repos\aws-sdk-net-staging\generator\ServiceClientGeneratorLib\Generators\SourceFiles\BasePaginator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Operation.Name));
            
            #line default
            #line hidden
            this.Write(" paginators.\r\n    /// </summary>\r\n    internal sealed partial class ");
            
            #line 25 "C:\repos\aws-sdk-net-staging\generator\ServiceClientGeneratorLib\Generators\SourceFiles\BasePaginator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Operation.Name));
            
            #line default
            #line hidden
            this.Write("Paginator : IPaginator<");
            
            #line 25 "C:\repos\aws-sdk-net-staging\generator\ServiceClientGeneratorLib\Generators\SourceFiles\BasePaginator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Operation.Name));
            
            #line default
            #line hidden
            this.Write("Response>, I");
            
            #line 25 "C:\repos\aws-sdk-net-staging\generator\ServiceClientGeneratorLib\Generators\SourceFiles\BasePaginator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Operation.Name));
            
            #line default
            #line hidden
            this.Write("Paginator\r\n    {\r\n        private readonly IAmazon");
            
            #line 27 "C:\repos\aws-sdk-net-staging\generator\ServiceClientGeneratorLib\Generators\SourceFiles\BasePaginator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Config.ClassName));
            
            #line default
            #line hidden
            this.Write(" _client;\r\n        private readonly ");
            
            #line 28 "C:\repos\aws-sdk-net-staging\generator\ServiceClientGeneratorLib\Generators\SourceFiles\BasePaginator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Operation.Name));
            
            #line default
            #line hidden
            this.Write("Request _request;\r\n        private int _isPaginatorInUse = 0;\r\n\r\n        /// <sum" +
                    "mary>\r\n        /// Enumerable containing all full responses for the operation\r\n " +
                    "       /// </summary>\r\n        public IPaginatedEnumerable<");
            
            #line 34 "C:\repos\aws-sdk-net-staging\generator\ServiceClientGeneratorLib\Generators\SourceFiles\BasePaginator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Operation.Name));
            
            #line default
            #line hidden
            this.Write("Response> Responses => new PaginatedResponse<");
            
            #line 34 "C:\repos\aws-sdk-net-staging\generator\ServiceClientGeneratorLib\Generators\SourceFiles\BasePaginator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Operation.Name));
            
            #line default
            #line hidden
            this.Write("Response>(this);\r\n");
            
            #line 35 "C:\repos\aws-sdk-net-staging\generator\ServiceClientGeneratorLib\Generators\SourceFiles\BasePaginator.tt"

foreach(var resultKey in this.Operation.Paginators.ResultKeys.Where(r => r.ListItemType != null))
{

            
            #line default
            #line hidden
            this.Write("\r\n        /// <summary>\r\n        /// Enumerable containing all of the ");
            
            #line 41 "C:\repos\aws-sdk-net-staging\generator\ServiceClientGeneratorLib\Generators\SourceFiles\BasePaginator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(resultKey.Member.PropertyName));
            
            #line default
            #line hidden
            this.Write("\r\n        /// </summary>\r\n        public IPaginatedEnumerable<");
            
            #line 43 "C:\repos\aws-sdk-net-staging\generator\ServiceClientGeneratorLib\Generators\SourceFiles\BasePaginator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(resultKey.ListItemType));
            
            #line default
            #line hidden
            this.Write("> ");
            
            #line 43 "C:\repos\aws-sdk-net-staging\generator\ServiceClientGeneratorLib\Generators\SourceFiles\BasePaginator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(resultKey.Member.PropertyName));
            
            #line default
            #line hidden
            this.Write(" =>\r\n            new PaginatedResultKeyResponse<");
            
            #line 44 "C:\repos\aws-sdk-net-staging\generator\ServiceClientGeneratorLib\Generators\SourceFiles\BasePaginator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Operation.Name));
            
            #line default
            #line hidden
            this.Write("Response, ");
            
            #line 44 "C:\repos\aws-sdk-net-staging\generator\ServiceClientGeneratorLib\Generators\SourceFiles\BasePaginator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(resultKey.ListItemType));
            
            #line default
            #line hidden
            this.Write(">(this, (i) => i.");
            
            #line 44 "C:\repos\aws-sdk-net-staging\generator\ServiceClientGeneratorLib\Generators\SourceFiles\BasePaginator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(resultKey.PropertyName));
            
            #line default
            #line hidden
            this.Write(" ?? new ");
            
            #line 44 "C:\repos\aws-sdk-net-staging\generator\ServiceClientGeneratorLib\Generators\SourceFiles\BasePaginator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(resultKey.Member.DetermineType()));
            
            #line default
            #line hidden
            this.Write("());\r\n");
            
            #line 45 "C:\repos\aws-sdk-net-staging\generator\ServiceClientGeneratorLib\Generators\SourceFiles\BasePaginator.tt"

}

            
            #line default
            #line hidden
            this.Write("\r\n        internal ");
            
            #line 49 "C:\repos\aws-sdk-net-staging\generator\ServiceClientGeneratorLib\Generators\SourceFiles\BasePaginator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Operation.Name));
            
            #line default
            #line hidden
            this.Write("Paginator(IAmazon");
            
            #line 49 "C:\repos\aws-sdk-net-staging\generator\ServiceClientGeneratorLib\Generators\SourceFiles\BasePaginator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Config.ClassName));
            
            #line default
            #line hidden
            this.Write(" client, ");
            
            #line 49 "C:\repos\aws-sdk-net-staging\generator\ServiceClientGeneratorLib\Generators\SourceFiles\BasePaginator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Operation.Name));
            
            #line default
            #line hidden
            this.Write("Request request)\r\n        {\r\n            this._client = client;\r\n            this" +
                    "._request = request;\r\n        }\r\n#if BCL\r\n        IEnumerable<");
            
            #line 55 "C:\repos\aws-sdk-net-staging\generator\ServiceClientGeneratorLib\Generators\SourceFiles\BasePaginator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Operation.Name));
            
            #line default
            #line hidden
            this.Write("Response> IPaginator<");
            
            #line 55 "C:\repos\aws-sdk-net-staging\generator\ServiceClientGeneratorLib\Generators\SourceFiles\BasePaginator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Operation.Name));
            
            #line default
            #line hidden
            this.Write(@"Response>.Paginate()
        {
            if (Interlocked.Exchange(ref _isPaginatorInUse, 1) != 0)
            {
                throw new System.InvalidOperationException(""Paginator has already been consumed and cannot be reused. Please create a new instance."");
            }
            PaginatorUtils.SetUserAgentAdditionOnRequest(_request);
");
            
            #line 62 "C:\repos\aws-sdk-net-staging\generator\ServiceClientGeneratorLib\Generators\SourceFiles\BasePaginator.tt"

foreach(var inputToken in this.Operation.Paginators.InputTokens)
{

            
            #line default
            #line hidden
            this.Write("            var ");
            
            #line 66 "C:\repos\aws-sdk-net-staging\generator\ServiceClientGeneratorLib\Generators\SourceFiles\BasePaginator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(inputToken.Member.ArgumentName));
            
            #line default
            #line hidden
            this.Write(" = _request.");
            
            #line 66 "C:\repos\aws-sdk-net-staging\generator\ServiceClientGeneratorLib\Generators\SourceFiles\BasePaginator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(inputToken.PropertyName));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 67 "C:\repos\aws-sdk-net-staging\generator\ServiceClientGeneratorLib\Generators\SourceFiles\BasePaginator.tt"

}

            
            #line default
            #line hidden
            this.Write("            ");
            
            #line 70 "C:\repos\aws-sdk-net-staging\generator\ServiceClientGeneratorLib\Generators\SourceFiles\BasePaginator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Operation.Name));
            
            #line default
            #line hidden
            this.Write("Response response;\r\n            do\r\n            {\r\n");
            
            #line 73 "C:\repos\aws-sdk-net-staging\generator\ServiceClientGeneratorLib\Generators\SourceFiles\BasePaginator.tt"

foreach(var inputToken in this.Operation.Paginators.InputTokens)
{

            
            #line default
            #line hidden
            this.Write("                _request.");
            
            #line 77 "C:\repos\aws-sdk-net-staging\generator\ServiceClientGeneratorLib\Generators\SourceFiles\BasePaginator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(inputToken.PropertyName));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 77 "C:\repos\aws-sdk-net-staging\generator\ServiceClientGeneratorLib\Generators\SourceFiles\BasePaginator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(inputToken.Member.ArgumentName));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 78 "C:\repos\aws-sdk-net-staging\generator\ServiceClientGeneratorLib\Generators\SourceFiles\BasePaginator.tt"

}

            
            #line default
            #line hidden
            this.Write("                response = _client.");
            
            #line 81 "C:\repos\aws-sdk-net-staging\generator\ServiceClientGeneratorLib\Generators\SourceFiles\BasePaginator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Operation.Name));
            
            #line default
            #line hidden
            this.Write("(_request);\r\n");
            
            #line 82 "C:\repos\aws-sdk-net-staging\generator\ServiceClientGeneratorLib\Generators\SourceFiles\BasePaginator.tt"

for(var i = 0; i < this.Operation.Paginators.InputTokens.Count; i++)
{

            
            #line default
            #line hidden
            this.Write("                ");
            
            #line 86 "C:\repos\aws-sdk-net-staging\generator\ServiceClientGeneratorLib\Generators\SourceFiles\BasePaginator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Operation.Paginators.InputTokens[i].Member.ArgumentName));
            
            #line default
            #line hidden
            this.Write(" = response.");
            
            #line 86 "C:\repos\aws-sdk-net-staging\generator\ServiceClientGeneratorLib\Generators\SourceFiles\BasePaginator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Operation.Paginators.OutputTokens[i].PropertyName));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 87 "C:\repos\aws-sdk-net-staging\generator\ServiceClientGeneratorLib\Generators\SourceFiles\BasePaginator.tt"

}

            
            #line default
            #line hidden
            this.Write("                yield return response;\r\n            }\r\n");
            
            #line 92 "C:\repos\aws-sdk-net-staging\generator\ServiceClientGeneratorLib\Generators\SourceFiles\BasePaginator.tt"

if (this.Operation.Paginators.MoreResults != null)
{

            
            #line default
            #line hidden
            this.Write("            while (response.");
            
            #line 96 "C:\repos\aws-sdk-net-staging\generator\ServiceClientGeneratorLib\Generators\SourceFiles\BasePaginator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Operation.Paginators.MoreResults.PropertyName));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 97 "C:\repos\aws-sdk-net-staging\generator\ServiceClientGeneratorLib\Generators\SourceFiles\BasePaginator.tt"

}
else if (this.Operation.Paginators.InputTokens[0].IsListOrDict)
{

            
            #line default
            #line hidden
            this.Write("            while (");
            
            #line 102 "C:\repos\aws-sdk-net-staging\generator\ServiceClientGeneratorLib\Generators\SourceFiles\BasePaginator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Operation.Paginators.InputTokens[0].Member.ArgumentName));
            
            #line default
            #line hidden
            this.Write(".Count > 0);\r\n");
            
            #line 103 "C:\repos\aws-sdk-net-staging\generator\ServiceClientGeneratorLib\Generators\SourceFiles\BasePaginator.tt"

}
else if (this.Operation.StopPaginationOnSameToken)
{

            
            #line default
            #line hidden
            this.Write("            while (");
            
            #line 108 "C:\repos\aws-sdk-net-staging\generator\ServiceClientGeneratorLib\Generators\SourceFiles\BasePaginator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Operation.Paginators.InputTokens[0].Member.ArgumentName));
            
            #line default
            #line hidden
            this.Write(" != _request.");
            
            #line 108 "C:\repos\aws-sdk-net-staging\generator\ServiceClientGeneratorLib\Generators\SourceFiles\BasePaginator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Operation.Paginators.InputTokens[0].PropertyName));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 109 "C:\repos\aws-sdk-net-staging\generator\ServiceClientGeneratorLib\Generators\SourceFiles\BasePaginator.tt"

}
else
{

            
            #line default
            #line hidden
            this.Write("            while (!string.IsNullOrEmpty(");
            
            #line 114 "C:\repos\aws-sdk-net-staging\generator\ServiceClientGeneratorLib\Generators\SourceFiles\BasePaginator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Operation.Paginators.InputTokens[0].Member.ArgumentName));
            
            #line default
            #line hidden
            this.Write("));\r\n");
            
            #line 115 "C:\repos\aws-sdk-net-staging\generator\ServiceClientGeneratorLib\Generators\SourceFiles\BasePaginator.tt"

}

            
            #line default
            #line hidden
            this.Write("        }\r\n#endif\r\n#if AWS_ASYNC_ENUMERABLES_API\r\n        async IAsyncEnumerable<" +
                    "");
            
            #line 121 "C:\repos\aws-sdk-net-staging\generator\ServiceClientGeneratorLib\Generators\SourceFiles\BasePaginator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Operation.Name));
            
            #line default
            #line hidden
            this.Write("Response> IPaginator<");
            
            #line 121 "C:\repos\aws-sdk-net-staging\generator\ServiceClientGeneratorLib\Generators\SourceFiles\BasePaginator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Operation.Name));
            
            #line default
            #line hidden
            this.Write(@"Response>.PaginateAsync([System.Runtime.CompilerServices.EnumeratorCancellation] CancellationToken cancellationToken)
        {
            if (Interlocked.Exchange(ref _isPaginatorInUse, 1) != 0)
            {
                throw new System.InvalidOperationException(""Paginator has already been consumed and cannot be reused. Please create a new instance."");
            }
            PaginatorUtils.SetUserAgentAdditionOnRequest(_request);
");
            
            #line 128 "C:\repos\aws-sdk-net-staging\generator\ServiceClientGeneratorLib\Generators\SourceFiles\BasePaginator.tt"

foreach(var inputToken in this.Operation.Paginators.InputTokens)
{

            
            #line default
            #line hidden
            this.Write("            var ");
            
            #line 132 "C:\repos\aws-sdk-net-staging\generator\ServiceClientGeneratorLib\Generators\SourceFiles\BasePaginator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(inputToken.Member.ArgumentName));
            
            #line default
            #line hidden
            this.Write(" = _request.");
            
            #line 132 "C:\repos\aws-sdk-net-staging\generator\ServiceClientGeneratorLib\Generators\SourceFiles\BasePaginator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(inputToken.PropertyName));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 133 "C:\repos\aws-sdk-net-staging\generator\ServiceClientGeneratorLib\Generators\SourceFiles\BasePaginator.tt"

}

            
            #line default
            #line hidden
            this.Write("            ");
            
            #line 136 "C:\repos\aws-sdk-net-staging\generator\ServiceClientGeneratorLib\Generators\SourceFiles\BasePaginator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Operation.Name));
            
            #line default
            #line hidden
            this.Write("Response response;\r\n            do\r\n            {\r\n");
            
            #line 139 "C:\repos\aws-sdk-net-staging\generator\ServiceClientGeneratorLib\Generators\SourceFiles\BasePaginator.tt"

foreach(var inputToken in this.Operation.Paginators.InputTokens)
{

            
            #line default
            #line hidden
            this.Write("                _request.");
            
            #line 143 "C:\repos\aws-sdk-net-staging\generator\ServiceClientGeneratorLib\Generators\SourceFiles\BasePaginator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(inputToken.PropertyName));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 143 "C:\repos\aws-sdk-net-staging\generator\ServiceClientGeneratorLib\Generators\SourceFiles\BasePaginator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(inputToken.Member.ArgumentName));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 144 "C:\repos\aws-sdk-net-staging\generator\ServiceClientGeneratorLib\Generators\SourceFiles\BasePaginator.tt"

}

            
            #line default
            #line hidden
            this.Write("                response = await _client.");
            
            #line 147 "C:\repos\aws-sdk-net-staging\generator\ServiceClientGeneratorLib\Generators\SourceFiles\BasePaginator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Operation.Name));
            
            #line default
            #line hidden
            this.Write("Async(_request, cancellationToken).ConfigureAwaitEx();\r\n");
            
            #line 148 "C:\repos\aws-sdk-net-staging\generator\ServiceClientGeneratorLib\Generators\SourceFiles\BasePaginator.tt"

for(var i = 0; i < this.Operation.Paginators.InputTokens.Count; i++)
{

            
            #line default
            #line hidden
            this.Write("                ");
            
            #line 152 "C:\repos\aws-sdk-net-staging\generator\ServiceClientGeneratorLib\Generators\SourceFiles\BasePaginator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Operation.Paginators.InputTokens[i].Member.ArgumentName));
            
            #line default
            #line hidden
            this.Write(" = response.");
            
            #line 152 "C:\repos\aws-sdk-net-staging\generator\ServiceClientGeneratorLib\Generators\SourceFiles\BasePaginator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Operation.Paginators.OutputTokens[i].PropertyName));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 153 "C:\repos\aws-sdk-net-staging\generator\ServiceClientGeneratorLib\Generators\SourceFiles\BasePaginator.tt"

}

            
            #line default
            #line hidden
            this.Write("                cancellationToken.ThrowIfCancellationRequested();\r\n              " +
                    "  yield return response;\r\n            }\r\n");
            
            #line 159 "C:\repos\aws-sdk-net-staging\generator\ServiceClientGeneratorLib\Generators\SourceFiles\BasePaginator.tt"

if (this.Operation.Paginators.MoreResults != null)
{

            
            #line default
            #line hidden
            this.Write("            while (response.");
            
            #line 163 "C:\repos\aws-sdk-net-staging\generator\ServiceClientGeneratorLib\Generators\SourceFiles\BasePaginator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Operation.Paginators.MoreResults.PropertyName));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 164 "C:\repos\aws-sdk-net-staging\generator\ServiceClientGeneratorLib\Generators\SourceFiles\BasePaginator.tt"

}
else if (this.Operation.Paginators.InputTokens[0].IsListOrDict)
{

            
            #line default
            #line hidden
            this.Write("            while (");
            
            #line 169 "C:\repos\aws-sdk-net-staging\generator\ServiceClientGeneratorLib\Generators\SourceFiles\BasePaginator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Operation.Paginators.InputTokens[0].Member.ArgumentName));
            
            #line default
            #line hidden
            this.Write(".Count > 0);\r\n");
            
            #line 170 "C:\repos\aws-sdk-net-staging\generator\ServiceClientGeneratorLib\Generators\SourceFiles\BasePaginator.tt"

}
else if (this.Operation.StopPaginationOnSameToken)
{

            
            #line default
            #line hidden
            this.Write("            while (");
            
            #line 175 "C:\repos\aws-sdk-net-staging\generator\ServiceClientGeneratorLib\Generators\SourceFiles\BasePaginator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Operation.Paginators.InputTokens[0].Member.ArgumentName));
            
            #line default
            #line hidden
            this.Write(" != _request.");
            
            #line 175 "C:\repos\aws-sdk-net-staging\generator\ServiceClientGeneratorLib\Generators\SourceFiles\BasePaginator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Operation.Paginators.InputTokens[0].PropertyName));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 176 "C:\repos\aws-sdk-net-staging\generator\ServiceClientGeneratorLib\Generators\SourceFiles\BasePaginator.tt"

}
else
{

            
            #line default
            #line hidden
            this.Write("            while (!string.IsNullOrEmpty(");
            
            #line 181 "C:\repos\aws-sdk-net-staging\generator\ServiceClientGeneratorLib\Generators\SourceFiles\BasePaginator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Operation.Paginators.InputTokens[0].Member.ArgumentName));
            
            #line default
            #line hidden
            this.Write("));\r\n");
            
            #line 182 "C:\repos\aws-sdk-net-staging\generator\ServiceClientGeneratorLib\Generators\SourceFiles\BasePaginator.tt"

}

            
            #line default
            #line hidden
            this.Write("        }\r\n#endif\r\n    }\r\n}\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 190 "C:\repos\aws-sdk-net-staging\generator\ServiceClientGeneratorLib\Generators\SourceFiles\BasePaginator.tt"

    // The operation the marshaller will be used on
	public Operation Operation { get; set; }

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
